### ISSUE TITLE
Setting color palette throws TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by ergo70** [ChenglongMa/SkinToneClassifier#25]
When trying to set a custom palette, e.g. in code:

```
stone.process(
        tmp_path, image_type='color', n_dominant_colors=5, tone_palette=["#6f503c", "#81654f", "#9d7a54", "#bea07e", "#e5c8a62"], tone_labels=[1, 2, 3, 4, 5])
```

I get TypeError: unhashable type: 'list' in File "/Python/Python310/lib/site-packages/stone/api.py", line 73, in process skin_tone_palette = normalize_palette(tone_palette)

I think this is the correct way, but I might be wrong, otherwise this is a bug.

best regards

Ernst-Georg

**Comment by ChenglongMa** [comment]
Thanks for your feedback. I will check and fix it soon :)

**Comment by ergo70** [comment]
The same happens on the CLI:

stone -p "#6f503c #81654f #9d7a54 #bea07e #e5c8a6"

File "/Python/Python310/lib/site-packages/stone/__main__.py", line 123, in main
    specified_palette = normalize_palette(specified_palette)
TypeError: unhashable type: 'list'

**Comment by ChenglongMa** [comment]
Hi @ergo70,

Thank you so much for your valuable feedback.

I've fixed it and released a new version.

Please upgrade the library by running one of the following commands:

```bash
pip install skin-tone-classifier[all] --upgrade
```
or
```bash
pip install skin-tone-classifier --upgrade
```

Thanks!

**Comment by ergo70** [comment]
Yes, it works now as described.

Thank, you for fixing this.
