### ISSUE TITLE
Issue with processing .jpg images in folder using GUI

### ISSUE THREAD

**Issue by kcolombe** [ChenglongMa/SkinToneClassifier#31]
Using GUI Mode and having a lot of trouble with the processing of images. All images are .jpg and getting the following error when selecting an entire folder with 22 images:

The program is processing your images...
Please wait for the program to finish.

Processing images: 0%| | 0/1 [00:00<?, ?images/s]Kenneth is not found or is not a valid image.

Processing images: 100%|██████████| 1/1 [00:00<00:00, 1.77images/s]
Processing images: 100%|██████████| 1/1 [00:00<00:00, 1.77images/s]

Any ideas or troubleshooting?

**Comment by ChenglongMa** [comment]
Hi @kcolombe,

Thanks for your attention on this library.

Could you please provide more details of the issue?

1. It seems the library only processed one image.
2. Doesn't "Kenneth" exist?
3. Could CLI mode work as expected?

Thanks!

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @kcolombe,

Thanks for your information.

It is still difficult to guess the reason, so I'm developing a `log` function to log more details when processing.

From the VSCode terminal, it seems that the image `ColombeKenneth` caused the program to freeze.
Could you double-check if the image is valid?

If you don't mind sharing these images, I'd love to debug locally to fix this. Of course, you can wait and see if there are any previously undiscovered findings in the log function in the next version.

Thanks so much for your patience!

Best,
Chenglong

**Comment by ChenglongMa** [comment]
BTW, @kcolombe, could you please check the `result.csv` file to see which images were not successfully processed?

Thanks!

**Comment by kcolombe** [comment]
@ChenglongMa ,

I would be happy to share the images. What is the best way to do that from your side? 

Looking at the results it seems the images were fully processed:

![Capture](https://github.com/ChenglongMa/SkinToneClassifier/assets/84145867/00ed1c33-57c9-4f27-a884-05ece6fdfedd)

Best,
Ken

**Comment by ChenglongMa** [comment]
Hi @kcolombe,

Thanks for your information!

It seems that `ColombeKenneth.jpg` was processed successfully. It should be another unknown image that froze the process.

The easiest way for me is to get all 22 of your images so I can completely reproduce your experimental process.

Would this work for you?

This is my email address: chenglong.m _at_ outlook.com.

Thanks!

**Comment by kcolombe** [comment]
I'll send it over right away...thank you!
