### ISSUE TITLE
Customise tone palette

### ISSUE THREAD

**Issue by nadia886** [ChenglongMa/SkinToneClassifier#32]
# Question
Hi, i've tried running your skin tone classifier on google colab and the results are wonderful! I would like to use it for my thesis project, and i want to customise the tone palette but it didn't work... Do you mind helping me?

Thank you very much!

**Comment by ChenglongMa** [comment]
Hi @nadia886,

No problem! Do you mind sharing the custom palette? Then I can try to generate a running command for you.

Thanks!
Chenglong

**Comment by nadia886** [comment]
Thank you for the quick reply, I appreciate it.

This is the custom palette,
1. #f3cd9f 
2. #f5c69a
3. #e8c5af 
4. #ebc086 
5. #e2ac90 
6. #ddb59e
7. #dea56e
8. #d99959
9. #c17936 
10. #bf7e44

**Comment by ChenglongMa** [comment]
Hi @nadia886,

Thanks for the information. I've made a demo on Google Colab to show how to use custom `tone_palette` when processing images.

Please visit it here: https://colab.research.google.com/drive/1VXif7XJoONo_3nxtkp6y2VfuqILtpDN5?usp=sharing

The core part of the demo is:

<img width="1124" alt="Screenshot 2024-12-06 at 11 17 28" src="https://github.com/user-attachments/assets/88fd3829-ab44-47af-9055-503358fa6aa7">

Please let me know if anything I can help :)

Best,
Chenglong

**Comment by nadia886** [comment]
Hi Chenglong,

It works well, thanks!! 

I have another question; do you know if I can deploy it as API with fastAPI? Because it is a library so I'm not really sure about it myself... Do you know how?

**Comment by ChenglongMa** [comment]
Hi @nadia886,

It's a good idea. I will try to implement it and get back to you soon :)

Thanks!

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @nadia886,

I've created a simple demo to show how to deploy the library with fastAPI:

```python
# Description: This is a simple FastAPI server that receives an image file 
# and processes it using the skin-tone-classifier library.

# requirements.txt:
#     fastapi
#     uvicorn
#     skin-tone-classifier
#     python-multipart

# Run the server:
#     uvicorn main:app --reload

from typing import Literal

import stone
from fastapi import FastAPI, UploadFile, HTTPException
from fastapi.responses import JSONResponse

app = FastAPI()


@app.post("/stone")
async def process_image(
        image_file: UploadFile,
        image_type: Literal["auto", "color", "bw"] = "auto",
        tone_palette: list = None,
        tone_labels: list = None,
        # other parameters...
):
    image_data = await image_file.read()
    temp_file_path = "/tmp/temp_image.jpg"
    with open(temp_file_path, "wb") as temp_file:
        temp_file.write(image_data)
    try:
        result = stone.process(
            temp_file_path,
            image_type=image_type,
            tone_palette=tone_palette,
            tone_labels=tone_labels,
            # other parameters...
        )
        result = JSONResponse(content=result)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    return result

```

To run the demo, please follow these steps:

1. Install required packages:
   * fastapi
   * uvicorn
   * skin-tone-classifier
   * python-multipart
2. Run the server:
   `uvicorn main:app --reload`
3. You can refine the implementation according to your project requirements.
4. Finally, you can use Postman or other HTTP Clients to test the API.

Hope this can help you!

Best,
Chenglong

**Comment by ChenglongMa** [comment]
Hi @nadia886,

I will close this issue since I haven't heard back from you yet. Feel free to reopen it if you need other help :)

**Comment by nadia886** [comment]
Hi Chenglong,

I hope your week is going well. I'm so sorry for not replying earlier as I've been busy with other things. I'll try your demo as soon as possible and get back to you! 

Thank you very much for your assistance :))
