### ISSUE TITLE
Error processing image 

### ISSUE THREAD

**Issue by Sasha95** [ChenglongMa/SkinToneClassifier#4]
If I don't use "--debug" comand, I get result.csv file with:
file,image type,face id,dominant 1,props 1,dominant 2,props 2,skin tone,PERLA,accuracy(0-100)
1,Error processing image 1: not enough values to unpack (expected 2, got 1)

With "--debug" I get for same image: 
file,image type,face id,dominant 1,props 1,dominant 2,props 2,skin tone,PERLA,accuracy(0-100)
1-1,bw,1,#BD9F99,0.64,#696156,0.36,#909090,BH,84.18

**Comment by ChenglongMa** [comment]
Hi @Sasha95,

Thanks for your feedback.
I will check and fix this bug soon!

Thanks!

**Comment by ChenglongMa** [comment]
Hi @Sasha95,

I have fixed this bug. Please install the latest version v0.2.2 by running:

```bash
pip install skin-tone-classifier --upgrade
```
Thanks!

**Comment by Oli2004** [comment]
ة؟إװؖإؓ؛ؙ؞ؗװ؞ؙؗؗؕآױ
