### ISSUE TITLE
Images using the black and white flag without specifying bw

### ISSUE THREAD

**Issue by wrightmk** [ChenglongMa/SkinToneClassifier#5]
If I run the command, `stone -i ~/<path to image> --debug` or explicitly give it the `color` option, `stone -i ~/<path to image> color --debug`, my image always appears in the bw folder and has the black and white color palette show up in debug mode. The only colored image I was able to get to work was the lena image from here http://www.lenna.org/. Any thoughts on what I'm doing wrong? Aside from that, great project!

**Comment by ChenglongMa** [comment]
Hi @wrightmk, thanks for your kind words!

It looks like the app has identified the image you want to process as a black and white image.
If you want to specify the image type manully, you can do the following:

```bash
stone -i ~/<path to image> --debug -t color
```
Or

```bash
stone -i ~/<path to image> --debug --image_type color
```

Please let me know if it still doesn't work.

Thanks!

**Comment by wrightmk** [comment]
The above commands still seem to classify the image using the black-and-white method. Here's a screenshot of the command I ran and the output. I also was meaning to mention that the --debug flag will hang at 0%. It still opens up the results window and just hangs in the command line.

<img width="1160" alt="Screenshot 2023-08-28 at 2 30 40 PM" src="https://github.com/ChenglongMa/SkinToneClassifier/assets/25016197/75f20f5e-5388-4ec2-80b6-da781fc481b4">

**Comment by ChenglongMa** [comment]
Hi @wrightmk, thanks for your feedback.

It's indeed a bug that the app cannot recognize the `image_type` option. I will fix it today.

The process bar hangs at 0% because the result window is still open. It will reach 100% if you close the window.
PS: The result window will pop up when only **one** image is processed.

**Comment by ChenglongMa** [comment]
Hi @wrightmk. I've fixed the bug and released the new version.
Please run 
```bash
pip install skin-tone-classifier --upgrade
```
to upgrade the library to the latest version.

Thanks again for your feedback.

**Comment by wrightmk** [comment]
Hi @ChenglongMa, thanks for addressing this! Works as intended now!

> Hi @wrightmk, thanks for your feedback.
> 
> It's indeed a bug that the app cannot recognize the `image_type` option. I will fix it today.
> 
> The process bar hangs at 0% because the result window is still open. It will reach 100% if you close the window. PS: The result window will pop up when only **one** image is processed.

In Response to the process bar hanging, there is no ability to close the window. If you see my screenshot above, there's only window is only able to be minimized (no red dot).

**Comment by ChenglongMa** [comment]
Hi @wrightmk,

I'm glad it is working now :)

You can press *any* key to close the window whilst the window is **in focus**. 
Please note that if the command line is in focus then nothing happens. (Refer to https://stackoverflow.com/a/28322925/8860079)

**Comment by ChenglongMa** [comment]
Hi @wrightmk,

I will close this issue.
Feel free to reopen it if there are further problems.

Thanks!

**Comment by SlotthCode** [comment]
Nigger.
